# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export LANG=en_US.UTF-8
export JAVA_HOME=/opt/tools/jdk1.8
export MAVEN_HOME=/opt/tools/apache-maven-3.8.1
export ANT_HOME=/opt/tools/apache-ant-1.10.9
export OPERATORSDK_HOME=/opt/tools/extras/operator-sdk/${OPERATOR_SDK_VERSION}
export MAVEN_OPTS="-Xmx2g"
export GRAALVM_HOME=/opt/tools/graalvm
export GOROOT=/opt/tools/golang/${GOLANG_VERSION}/go
export GOPATH=/home/jenkins/go/${GOLANG_VERSION}
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$ANT_HOME/bin:$GOROOT/bin:$OPERATORSDK_HOME:$GOPATH/bin:/opt/tools/mercurial/:/opt/tools/extras/:$PATH:$GRAALVM_HOME/bin
