# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export LANG=en_US.UTF-8
export JAVA_HOME=/opt/tools/jdk1.8
export MAVEN_HOME=/opt/tools/apache-maven-3.6.3
export OPERATORSDK_HOME=/opt/tools/extras/operator-sdk
export MAVEN_OPTS="-Xmx2g"
export GRAALVM_HOME=/opt/tools/graalvm
export GOROOT=/opt/tools/go
export GOPATH=/home/jenkins/go
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$GOROOT/bin:$OPERATORSDK_HOME/v1.2.0:$GRAALVM_HOME/bin:$GOPATH/bin:/opt/tools/mercurial/:/opt/tools/extras/:$PATH