---

- debug: msg="WEBHOOK_URL \"{{ lookup('env','WEBHOOK_URL') }}\""
- debug: msg="TARGET_URL \"{{ lookup('env','TARGET_URL') }}\""

- name: Copy Pulp repos config - RHEL 7
  copy:
    src: data/config/pulp/pulp-rhel7.repo
    dest: /etc/yum.repos.d/pulp.repo
    owner: root
    group: root
    mode: 0644

- name: Install packages - git
  yum:
    pkg: 'git'
    state: latest

# TODO revert after https://github.com/probot/smee-client/pull/162 is merged and smee-client released!!
#- name: Install Smee Client
#  npm:
#    name: smee-client
#    version: 1.1.0
#    global: yes
#    production: yes
#    state: present
#    registry: ${NPM_REGISTRY_URL}

- name: Transfer the script
  copy:
    src: data/service/smee-client-build.sh
    dest: /root/
    mode: 0777

- name: Build Smee Client from fork
  command: bash /root/smee-client-build.sh

- name: Generate smee.service.sh file
  template:
    src: data/service/smee.service.sh.j2
    dest: /usr/local/bin/smee.service.sh
    mode: 0777
    force: yes
    owner: root
    group: root

- name: Get smee.service content
  shell: cat /usr/local/bin/smee.service.sh
  register: cat

- debug: msg="{{ cat.stdout }}"

- name: Register Smee Service
  copy:
    src: data/service/smee.service
    dest: /etc/systemd/system/smee.service
    owner: root
    group: root
    mode: 0644

- name: Start Service
  service:
    name: smee
    enabled: yes
    state: restarted

- name: get smee status
  command: systemctl status smee.service
  register: smee_service_status

- debug: msg="{{ smee_service_status.stdout }}"

...