---
- name: "Print webhook and target variables"
  debug: msg="webhook_url:{{ webhook_url }}; target_url:{{ target_url }}"    

- name: Copy Pulp repos config - RHEL 7
  copy:
    src: data/config/pulp/pulp-rhel7.repo
    dest: /etc/yum.repos.d/pulp.repo
    owner: root
    group: root
    mode: 0644

- name: Install packages - git
  yum:
    pkg: 'git'
    state: latest

# TODO revert after https://github.com/probot/smee-client/pull/162 is merged and smee-client released!!
#- name: Install Smee Client
#  npm:
#    name: smee-client
#    version: {{ smee_client_version }}
#    global: yes
#    production: yes
#    state: present
#    registry: ${NPM_REGISTRY_URL}

- name: Transfer the script
  copy:
    src: data/service/smee-client-build.sh
    dest: /root/
    mode: 0777

- name: Build Smee Client from fork
  command: bash /root/smee-client-build.sh

- name: Generate smee.service.sh file
  template:
    src: data/service/smee.service.sh.j2
    dest: /usr/local/bin/smee.service.sh
    mode: 0777
    force: yes
    owner: root
    group: root
  notify:
    - start smee service

- name: Get smee.service.sh content
  shell: cat /usr/local/bin/smee.service.sh
  register: smee_content

- name: Print smee.service.sh content
  debug: "msg={{ smee_content.stdout_lines }}"

- name: Register Smee Service
  copy:
    src: data/service/smee.service
    dest: "{{ smee_service_path }}"
    owner: root
    group: root
    mode: 0644

- name: Get smee.service content
  command: cat {{ smee_service_path }}
  register: smee_service_content

- name: Print smee.service content
  debug: "msg={{ smee_service_content.stdout_lines }}"   
...