---
### Add Repository dnf ###

- name: Add GH-CLI repository
  yum_repository:
    name: gh-cli
    description: GitHub CLI Repo
    baseurl: https://cli.github.com/packages/rpm/gh-cli.repo

### Install gh-cli package ###

- name: Install packages
  yum:
    pkg: ['gh']
    state: latest

...