---
### Install dnf ###

- name: Install dnf
  yum:
    pkg: ['dnf']
    state: latest

- name: Install gh-cli.repo
  command: dnf install 'dnf-command(config-manager)'

### Install required gh-cli repo ###

- name: Install gh-cli.repo
  command: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
  

### Install required gh-cli repo ###

- name: Install gh-cli.repo
  command: dnf install gh -y

...