---
### redhat root certs ###

- name: Download root certs
  get_url:
    url: "{{ cert_url }}/{{ item }}"
    dest: "{{ cert_files_folder }}/"
    validate_certs: no
  with_items:
    - "{{ cert_file_list }}"

- name: Create cacerts directory
  file:
    path: /etc/openldap/cacerts
    state: directory
    recurse: yes

- name: Copy legacy root certs to cacerts
  copy:
    src: "{{ cert_files_folder }}/{{ item }}"
    dest: /etc/openldap/cacerts/
    remote_src: yes
  with_items:
    - "{{ cert_file_list }}"

- name: Assure authconfig package is installed
  package:
    name: authconfig
    state: 'present'

- name: Rehash cacerts
  command: cacertdir_rehash /etc/openldap/cacerts

- name: Update ca trust
  command: update-ca-trust

- name: Make node.js use the system root CA
  copy:
    dest: /etc/profile.d/nodejscerts.sh
    mode: 0755
    content: |
      export NODE_EXTRA_CA_CERTS={{ cert_files_folder }}/{{ nodejs_cert }}


### ssh config ###

- name: Set no strict host checking
  shell: echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

...