---
- name: "Print encrypted_password variable"
  debug: msg="encrypted_password:{{ encrypted_password }}"      

- name: Install verdaccio
  npm:
    name: verdaccio
    version: "{{ verdaccio_version }}"
    global: yes
    production: yes
    state: present
    registry: ${NPM_REGISTRY_URL}

- name: Generate verdaccio.service.sh file
  template:
    src: data/service/verdaccio.service.sh.j2
    dest: /usr/local/bin/verdaccio.service.sh
    mode: 0777
    force: yes
    owner: root
    group: root
  notify:
    - "start verdaccio service"

- name: Create verdaccio directory
  file:
    path: /verdaccio
    state: directory
    mode: 0775    

- name: Copy verdaccio Configuration
  template:
    src: data/config/verdaccio/config.yaml.j2
    dest: "{{ verdaccio_config_path }}"
    mode: 0777
    force: yes
    owner: root
    group: root
  notify:
    - "start verdaccio service"

- name: Copy Verdaccio user/pass
  template:
    src: data/config/verdaccio/htpasswd.j2
    dest: "{{ verdaccio_htpasswd_path }}"
    mode: 0777
    force: yes
    owner: root
    group: root
  notify:
    - "start verdaccio service"

- name: Register Verdaccio Service
  copy:
    src: data/service/verdaccio.service
    dest: /etc/systemd/system/verdaccio.service
    owner: root
    group: root
    mode: 0644

- name: Get verdaccio.service content
  shell: cat /etc/systemd/system/verdaccio.service
  register: verdaccio_service_content

- name: Print verdaccio.service content
  debug: "msg={{ verdaccio_service_content.stdout_lines }}"

- name: Assure firewalld package is installed
  package:
    name: firewalld
    state: 'present'

- name: firewall setup
  firewalld:
    state: enabled
    port: "{{ verdaccio_service_port }}/tcp"
    permanent: yes
  notify:
    - "reload service firewalld"

...